language: node_js
node_js:
  - 4.3.2
sudo: false
cache:
  directories: node_modules
before_script:
  - npm install -g gulp
script: gulp test
deploy:
  - provider: lambda
    access_key_id: "${AWS_ACCESS_KEY}"
    secret_access_key: "${AWS_SECRET_KEY}"
    function_name: "carport-login"
    role: "${AWS_LAMBDA_ROLE}"
    zip: "${TRAVIS_BUILD_DIR}/dist.zip"
