language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  edge: true
  provider: lambda
  access_key_id:
    secure: Z48yrRWYFJRwrAyZkmF9S4qVlC4s0+dQY7htmZhQoLh1a7KosvTw/Nj4vY+0fmwDe/44eufQXU4DWKjJKVCC+1yLwYv+1pUn2LKKPB9PTSljyz0Gzui7LnpdETHUAis289zZinLowaMBNHPv4GbrQAUjwduaqN17Eh0TZBELCcNFwRE9rd3vPQ3nJz511DTUuxiU0UTk/60YEQb3GmmMq1CSyf8le6wDUZKzqzhZVflC1+wDiUTVSTmrQXgM1rdwXYyUlUQNjw4cGYkrFfOg+myCvezowqV2aQuG4DTm2Er3n0+afCKgtMlcPeg33ecg5K16PI5iJB6PM9gcY7LprU6ilrIq7gOg2d724u9dbbK//cwkbOKtg/RE6sw9CdXUPXtStJbGSY/CPYQ9fFrk8n5s0uvuLKEvgqWdjx2gb+SmY6eM4Z5caobSwVOmf7IClq6ZSWF72XSDoF8czsZfRHEXSS7w/UQP+QrhkGq2jqhKEPLPNM9sO4Fojpc5FcafNdUEmPPwXNECtuepU7/DpEETt2XPeTw5l/UGb45cl06sqU1Ufg/zXMLsjTdMVD1pqo3ufJcwPPU83L6IiWZQCnTxjjKgSzawvOmKzPPYvomdGmLMFE0L3B0opvCNP7S9wx+MXQg4+VJ66JKAycblHJ1MtF3XiKU4L+CkfUNQNeY=
  secret_access_key:
    secure: k+1qQpYwLX536vZm+/WY9XdJXO/iKYH0IJ0k6pkh8nGD4AU3mSRsJsSGJ3Xhda3Gmmqao3+K1fw+wAAW1GYjySksK3NrTrbv+lSbjTaarP0kMJdRMgaDEVctoWmairftfM1yAUEaUUmEBRqTSGsmpWPq5sHEpSDHI0UaBVA1GOmmFcuelDC/tEOqJyh6O4ulU/qeQyoNXeEexMGeimNsr/nzVpqkcJaSMaxNA5qcb1DJUy6cXRtKT9lBLODSI9Hgsv8iZZdKqG+a173XgBug4vYCS96dDJhEi4oGcALfI06EhSSqnsyRN6xiS5i6kwPaMxTYYhnzWKHAqUsVGRn/vwb8O/OvKu9oXp18OgM74YOP6UynxjOyWDKWwkm2ni7NGqHNv7wdpCcu4qch3m+0sgfG7xuP6wIhcliFqa2GJ8xvFUb0oDKs/YuE8RyWe6GVt8hOZQb+kbOMuzT6LfXRrBpCxiFypYHMUDs7fT6VRhB+IcNRm8sP2K9UBDAq36sb7jmBL/h6cBVS1VBZWRgE7vdHagVShMnSzQbV0MQWsjVCP7NeEWsCdiN/AzsXO2XCPeNK6pJ1LFbmKn+VPCeFR1C7lFFwGZXf+gZXCO0jXHz1hDhelXRFX6zVTofFFY0YoZMKTzC163gPpqthR+gBoQzyIQ+lFT6MZ3L7lmbiqvA=
  skip_cleanup: true
  function_name: carport-login
  handler_name: handler
  runtime: nodejs4.3
  role: arn:aws:iam::710331364289:role/api_lambda_dynamo
  zip_file: dist.zip
