language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  edge: true
  provider: lambda
  access_key_id:
    secure: DHXJ8xbbN5YQsm2Rn+C1lIl7naB6guEF3Mn2W745mFe7ylie8/EltB1qONbrb9/+Em4qndxHJFVy4ypN62q6ys7Uulvys5vPNKF7RCJd2ZW/fpZHFp6B7nfAOsn5wRgs9nrJgqO5E39V4GahVGZuhAcAe1SEpHjnDhyFvC3nqc+EJ+LVFlPXg0qjF1F1BMHpl6L+WM9EVlD0EaGMyQRN087W8NhzxME4tqUaRYxccU8MuockN3xxDTD+yS2dTTSQNH4AlTrc60rzj4XmJLnE+XzrU110uDtwy5uieylRtulkLIYKf3E+nQzkvK/AMPZ5osk+ioMqbL7rf1tQAh5BJXnAxl4Rep/t8lZHGG1CTqXvdeVMgnrw7wS3x4FhrR3SkuPyaA/AlFdi8ri7w03Eb2qYur/iQGWknRDPR9dLIw9+7uOk7PisZ51N64xEjzT3H9SD+RiwjsLJpEll2A7l9W924nqVyknm7cBERMoGQFOL07QWw4PwdK/UwoyaLHSIrJhTSXEbp0aKwmb45v09G7Qd7CGWq0t97WNO+Y29eWD1lJeEh1TxARDRomqBq5WGC+GG9pQw7Uwn1x7+LbxbmvomBa010M76IAlObb9jV3cibXg6W1B3zexdnvooHasudHzLDJHZpck8wUNTcOAzMSs6h9lt0ShCZhhCdbYIjyI=
  secret_access_key:
    secure: i6lCgLgvMRMkl1t9UJy9sMw+6vMApe0yRBZMBmpMtzJfMWRXRHs7sMV6Iq5A1VpGNZl5zycUfaOMf9ztscTzeyEdTSk9USU9WjazohSyOI9b13brApnfkdDgfkYP/m3PHF/yR7aLPChEkhiOdCJlA9ns5b9Om4DfMiz6CnSXBdiWwRonb29cTYDwoz+PzLew6/5R1Tab2Dl+GjDDNgKNZLVK87LrhFA/ui5UKGhqcHuKwmR6Fzd4nPKZs2rlqxamP1eX64/RVrYXmKHgG7E77uTE68elaFCAjA7GkMvV9ugEXxDtCJjtFikfN/QJBmZc3iX9iQSBrK8eSS459OsL01U5SZLsOOwugRwx5lWW48CQ2CP1nQ68mXQOcrssOJak+LadOO9Hx183s+Izm7EjwUAF42Wx8c6bWBP23hNDx2OeUQWrVRTRFe3KOVep2C3Oiv/iLGOeFsQBl3pVqydUPfRElIl71jH234mVh1PRxLex4aXauNPSek62zbCeaRYWl6V1npOWCHzafuxB7O/3W00ervNKWZPjvJtx95Af1BZ4rHBsUF5UUAatbJ2jNqyK6t3xB44YUkojtMYlkv8nbZyENou5BLiEk87fQvG1gSabmwsyMGglU/hHSOEkSU0vu4ocXmhBLhf8Cik/R195C/pzkPQ8m+JsWfC36TIQh/U=
  skip_cleanup: true
  function_name: carport-login
  handler_name: handler
  runtime: nodejs4.3
  role: arn:aws:iam::710331364289:role/api_lambda_dynamo
  zip_file: dist.zip
