language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  edge: true
  provider: lambda
  access_key_id:
    secure: kyj15plHJRv2jydhvtaoWu9jIsAT2rW1q0qfuIOKlP0cESdqSFCjiQSG6Y+DGrQrm/O7cSAbd62YM+4qB9ZtVc+qCFNQ0/N90fFIiF21DGZ0Pb5P+Uj2G/9VLGsp+PhzBvT1Ls+fGuPDfLB3BxaAGut5GCUliJKoEZa7fhsJVeVnxa3jJ9RdCzpBo9P8zpB0nxKiFyJhUD81NQ2D6QzjEoHdLLAzP7hkAgvSr16Am6T1LTVrcLxu3RIwYrocKE/3+cgx90RLoSkIYjPp3k7RrjGVQcmKw4le6cRToijJ4Nd0hnkP+Xs1CsQp4aDRx+KXEaMaj4IHOVeDjv3XMj5JlMUyHAOMWGxvTZsaUy8xNmVwzz+2PW8VPvgeEecNd/tEfFeMULdMaKZnD8xgUO3lH7YEXX1nYp43GyLMHklhRN/NoHpAgWwNunnutnamkpN1QyjuN/wWr/BZNW/xaADPEw0btNTJwu+xiQsEeohibWOC0zi44mbdOGpceE65q2jZAlwAhQTcJs9kJh0XheeFqwtnMgN5u5Mb8rCconKshR6YqKLWznbIixm3fMapg7Q148hbAUR6CCBOixRmUVnysfJXUQYfqI7SEpcFIcW/pNV4bkJVLSdIIOL8T0LIELQf8K9UqPc4j/5nPo4N/sB3/yaukM7S7WAC12ZMLnxxSqs=
  secret_access_key:
    secure: FdQloULZWcPlMCRsFMQys3PKcs0j14nUJ0Kur+as+0wPNY3VL172QuE6QaCl7CzM93nydDoL80eGX9xzcIKkCbsbCf+KG1jgMwIG6dDLYXLgeikE+/FizkBFa8Le0WHdkkCP6s6ehiTp2BbfcQpdXuea3Ape5F/HyjnhkyT8Mt0CtClUThxstAHn6rWA9nfd0BAsRxuH8qqMPTUe+zk6YfPN1hnlgylpCpNzWcFdB/iR08BMgKZM9UN+ekNU1Z+TNCDEk3RjOoypvnycMr0bUTSEzZGNWuO1Qg3RcnjOyKIh4T/67Jo7XthgpoZBXaYtPWc3rhdtLi3s0OCyjRnNxf+5aYl94R8Psy1C9PZcmYattioY7akBIM0oVJmK/2PLgksBA+t7SB5TMBF616BcRJW7ygQzFo1XNZPhu6SuSKjNnKEmKNIHlUJYutQ2GnZGL8kvTxs0iEX6iRnyKAFQjPc3rqtDvM2GPw1Eeh3AjZQTq4T56v/Z0e205xT22chPimlafIwXP4rRlpLy4OYE1YEkzVmlI7jHB1TmCxSeVHx9ElUkb0ZjeDETQu0Kos+fWwJj5aCEvrulYdDhYbddpqQMrglRjyPzxmRp4dBiVLDD3z0VNEgRE0kbt5oFvlITqAO4eoPo493QCcBEod2P2uXICce80eBeHLIv0qQfxdA=
  skip_cleanup: true
  function_name: carport-login
  handler_name: handler
  runtime: nodejs4.3
  role: arn:aws:iam::710331364289:role/api_lambda_dynamo
  zip_file: dist.zip
  
