language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  provider: lambda
  skip_cleanup: true
  edge: true
  access_key_id:
    secure: mMTIDeJMeDIAIQLEO1/PDCIxCkPExe96UHqyTQlMfm+jvfAPe1VFkpV2OHGhwXUiL1QWpArLjh1eHEghMbt2EWnC8kxpk9z9xX3RQI+1ZIkhNSfmN7BOVroRDlCi5a/OofWMtsL7944cjK6zo9fj8nzVcW8puzUDNOccTFUEiztXTq7uueSefCLEf3GoMXFli/Q5EHD/MdbOhy1iY7Vr3bf3yG77feQfekKqgPsr+gV80BSmewjkJqMnd6UESegGei29oaaoNpvePqqDFeIhjSS0JxWiSHwpo8IdO7Oqvq627fChJGgbM3mXMLUtqCOQ72imNRtltXWHDiGeJHRm4i+0/4ibE8dCOQYDiC5yRR7zzwuYPnOWBZE6WgCN9kZiNmwhAMClFL2SdnJtWPM4p7gLQkq92wbbRtXxrZfzFY9oMylfWsxhGuBOnRqmhJJ8MjffPD+nZ5PiRRnt8YoASghnWC/AnVDLXlNh6whc1MeIzXMwHQ2Jd+//7nA26X3xwQ3WmdxaERaKycJSTy14B/NSnyVI316XZxuBFhGdymQixZuieKt7mXP3eeC0vK/B+T9gHjIgr5mFj9A3nXLp+2gTuAsvblL49y06UiQhy5Si3x9A77Y7o+Xe3MSnbeVfp0gkDs62vJpujItTPq/HH+9SG03Db1Blsens48Z1/+w=
  secret_access_key:
    secure: B8+b4QOpBs3IzmkFOZHC13b2z7475OZGkeGHX54o6iqdlRkLHnMpsXIMLmQ78IjQChryBBu9+NGJMtoZLdhjnGXAjj0pJbxOCAXayad1AHtbuFxHDlstgfWfXtI5w+ehTauTmwHuuELuRSqhL1AVQvVOwfzBpuUKxQ9IyHNfs3SuSSCJ6bdJsJjeEWIwfwrKZJ9Ltl3X5NP30OtnkqzQ9p5fNBTv3UO0rM6RUMNL3gPcigq+XhEvtW7v9ud4Xg4dOVVvBZhZ/CG55RlwADE82xDmr+Wwmk/YNMKxDl3A8lVKhUNuG6gu2zLJ6glNn96l6H5HYxSMzg7K1ZWghgeF7bY1om2P0oWmjieuc+UqijcuLpvg250ONZv8kjCIeSIFrK45Aw7Fs1Mq2lLB5WGO97nivXd6dsbDSn8AmAC8CGwRSzLaouMfnwjwpCmEd/CYtyAxiIJXMDaIb2bdDA790ph90n6xe1xXDANz2vaQMRDI/r9Th1H9VSazFFv2TCaX7xKRKneoUEF11aM5V5DYniS5RdcZqncTEzWjwD3mEBfIu7fYX7Gw0QzDVGkmfXGz7whOFr+j4cYy9LBkWXdUKskAtZRXchydR3ycb6g5HuTYWQ5keUP2gyX4lky3ZoBar3UgAmt/t0f43HIGs3WQxzwF0zlnDyFClhsmNo3QJaw=
  function_name: carport-login
  handler_name: handler
  runtime: nodejs4.3
  role: arn:aws:iam::710331364289:role/api_lambda_dynamo
  zip_file: dist.zip
before_install:
- openssl aes-256-cbc -K $encrypted_c3fce271baf6_key -iv $encrypted_c3fce271baf6_iv
  -in carport-secret.json.enc -out carport-secret.json -d
