language: node_js
node_js:
- 4.3.2
sudo: required
dist: trusty
cache:
  directories: node_modules
before_script:
- npm install -g gulp
script: gulp test
after_success: gulp dist
deploy:
  provider: lambda
  skip_cleanup: true
  edge: true
  access_key_id:
    secure: KXWJwlvYE0jgMJH6Ja8Vd8fub9eXsI5At4Qf7p0Gry3xabVKBcO4y8a1zRVUURiis4RlwxG9UXrYtGNKEbkoS+Ieb3+aBP0/x6k8G420AXzkV89lc/UL1qcNvTI2lT2SyVDOntwibof/4wovrTNIWAj+1mjANNZKCorWrnLPkIJKeMUsSLeR7zIwKGOsF/K8aith6V+bLbStge2PNxWTxx8rO37HRSJpZRq+JyyjeSKS4vRbXvLtQNPIgIrXx9cIEuhlplCFJQFvIt6KgT09G3kMIsMP4D5uU1BUB7KC4cE5xHN6cs4Tn05SZMXaYRWj5fi7KPlo8hMm4tyP2GOgesGfX3qq4DJTyFU4803v4I6x0TuSTRXQ6P0h8IYZhONh/AtFa0NP+4bso/uwWx5t4D7OST+y6+8jsVZrsK3UT45yLuQmv11KLFx0IdFk5mtsqMHZW6PHubT/a1SHZAhafKOAfGBLiU34CwMQ5k6wqDJ89GsqWyIl45ANcyyD4g+INAp+j5bfJTXSuOA8yTO5sZ8fRDW8VqonpCKzSSxQ3RTfjl9lERnezUJHatHsgNfaygHXHsTw7JagLJONLhUPYnoh71djG8YWEdjzwsi/0k9tdpblnXuO//DpoQBegHBljeCnHJzpY7H8Pg+YEkpMbZu/lu+JCddSLqIk9hI3sy4=
  secret_access_key:
    secure: lOK6nEVJysM22I3ARKQU4tlmODrrMdU6mhG718s9/FxT021q2hHajrCyGIhutMN4kdGMMbKXH1lhiXWzUIhQvnWpIKTNJ7OXYAXZYelZTp+pimWDzfS5/DQsCD9mBvF0SLK6qaDjSJloZwgY+HLeJDkBvwzv9v2kB+U2rB631XPbOri8mGXoqbheuZ2nUv4b/o4kZmofC/Qkuo6jX1/ufNrXe+uelmtwoRxwXi8+cu7axJFB72DPxpYT/f3ZhJVVR8RLjuvLS1Xzj7GpM0u9w9ID9JqkHVRN3Tpu/8oleQAJfa/inDbxp5nLz8rvtjow2mYLmzB5+qh2psrTZTSRILPXNoW5qXrbwewOaXFCfcwq4e9VBsiYKGh852Of8zXbxjcfwdoxKp2eHkcw3HAUrIc2fEqXiItAaPS9QIZ/jDXwj7t3Kt3ymRkYlQ1X3lz7e9J6YZwxBKtkFY44FRYJLuord4vn+A+Rbr3tiq1lYYk45ksPyHT8OXEpVKtlOgnVqZiPJHw2Vj53j74pg4z9lzrjMcnJeH1aEuimVXW+2UJsFUla7ATU/2ahAI4cdf52AkSUVPC1Y3adZf5YC9umeOAOnlhR6ESkXjxH4W8AD5C8FDGskHEuteJ5tKx7O51lXTJT+Cna4VI3Zh+yf26x/qoIutdHUhUITHF/9bQlcfY=
  function_name: carport-login
  handler_name: handler
  runtime: nodejs4.3
  role: arn:aws:iam::710331364289:role/api_lambda_dynamo
  zip_file: dist.zip
